import dotenv from 'dotenv';
import { z } from 'zod';

dotenv.config();

const ConfigSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  BOT_PREFIX: z.string().default('.'),
  PORT: z.string().transform(Number).default('3001'),
  HANDLE_SELF_MESSAGES: z.string().transform((value) => value === 'true').default('true'),
  HANDLE_INCOMING_MESSAGES: z.string().transform((value) => value === 'true').default('true'),
  OWNER_NUMBER: z.string().optional(),
  AUTH_PHONE_NUMBER: z.string().optional(),
  OWNER_NAME: z.string().default('Owner'),
  DASHBOARD_URL: z.string().default('http://localhost:3001'),
  SCRIPT_URL: z.string().optional(),
  DONATE_TEXT: z.string().optional(),
  RULES_TEXT: z.string().optional(),
  PERFECT_MATCH_NAME_1: z.string().optional(),
  PERFECT_MATCH_NAME_2: z.string().optional(),
  AI_API_BASE_URL: z.string().optional(),
  AI_API_KEY: z.string().optional(),
  AI_MODEL: z.string().optional(),
  AI_IMAGE_API_BASE_URL: z.string().optional(),
  AI_IMAGE_API_KEY: z.string().optional(),
  AI_IMAGE_MODEL: z.string().optional(),
  AI_IMAGE_ENDPOINT: z.string().optional(),
  AI_TTS_API_BASE_URL: z.string().optional(),
  AI_TTS_API_KEY: z.string().optional(),
  AI_TTS_MODEL: z.string().optional(),
  AI_TTS_VOICE: z.string().optional(),
  AI_STT_MODEL: z.string().optional(),
  AI_STT_LANGUAGE: z.string().optional(),
  AI_STT_TIMEOUT_MS: z.string().transform(Number).default('60000'),
  AI_EMBEDDING_API_BASE_URL: z.string().optional(),
  AI_EMBEDDING_API_KEY: z.string().optional(),
  AI_EMBEDDING_MODEL: z.string().optional(),
  AI_EMBEDDING_ENDPOINT: z.string().optional(),
  PUTER_AUTH_TOKEN: z.string().optional(),
  PUTER_CHAT_MODEL: z.string().optional(),
  PUTER_IMAGE_MODEL: z.string().optional(),
  PUTER_TTS_MODEL: z.string().optional(),
  PUTER_TTS_VOICE: z.string().optional(),
  PUTER_STT_MODEL: z.string().optional(),
  PUTER_TIMEOUT_MS: z.string().transform(Number).default('60000'),
  PUTER_RETRIES: z.string().transform(Number).default('1'),
  AI_MEMORY_ENABLED: z.string().transform((value) => value !== 'false').default('true'),
  AI_MEMORY_FILE: z.string().optional(),
  AI_MEMORY_MAX_MESSAGES: z.string().transform(Number).default('80'),
  AI_MEMORY_MAX_MB: z.string().transform(Number).default('5'),
  AI_MEMORY_OVERFLOW_MODE: z.enum(['compact', 'overwrite']).default('compact'),
  AI_MEMORY_MAX_TEXT_CHARS: z.string().transform(Number).default('1000'),
  DELETED_MESSAGE_RECOVERY_ENABLED: z.string().transform((value) => value !== 'false').default('true'),
  DELETED_MESSAGE_FILE: z.string().optional(),
  DELETED_MESSAGE_MAX_MESSAGES: z.string().transform(Number).default('500'),
  DELETED_MESSAGE_MAX_DELETED: z.string().transform(Number).default('100'),
  DELETED_MESSAGE_MAX_TEXT_CHARS: z.string().transform(Number).default('4000'),
  DELETED_MESSAGE_MEDIA_ENABLED: z.string().transform((value) => value !== 'false').default('true'),
  DELETED_MESSAGE_MEDIA_DIR: z.string().optional(),
  DELETED_MESSAGE_MEDIA_MAX_MB: z.string().transform(Number).default('25'),
  DELETED_MESSAGE_MEDIA_STORAGE: z.string().transform((value) => value === 'mega' ? 'mega' as const : 'local' as const).default('local'),
  DELETED_MESSAGE_MEDIA_MAX_TOTAL_MB: z.string().transform((value) => Number(value || '1024')).default('1024'),
  MEGA_EMAIL: z.string().optional(),
  MEGA_PASSWORD: z.string().optional(),
  MEGA_FOLDER_PATH: z.string().optional(),
  MEGA_2FA_CODE: z.string().optional(),
  AI_ENABLE_TOOLS: z.string().transform((value) => value !== 'false').default('true'),
  AI_DEBUG: z.string().transform((value) => value === 'true').default('false'),
  IGNORE_NEWSLETTER_MESSAGES: z.string().transform((value) => value !== 'false').default('true'),
  OPENROUTER_API_KEY: z.string().optional(),
  OPENROUTER_MODEL: z.string().default('openrouter/free'),
  OPENROUTER_IMAGE_MODEL: z.string().optional(),
  OPENROUTER_TTS_MODEL: z.string().optional(),
  OPENROUTER_TTS_VOICE: z.string().default('alloy'),
  SPOTIFY_CLIENT_ID: z.string().optional(),
  SPOTIFY_CLIENT_SECRET: z.string().optional(),
  SPOTIFY_MARKET: z.string().optional(),
  IGNORE_OLD_MESSAGES_SECONDS: z.string().transform(Number).default('0'),
  STARTUP_IGNORE_MESSAGES_SECONDS: z.string().transform(Number).default('60'),
  SESSION_PATH: z.string().default('./sessions'),
  REDIS_HOST: z.string().default('localhost'),
  REDIS_PORT: z.string().transform(Number).default('6379'),
  REDIS_PASSWORD: z.string().optional(),
});

export const config = ConfigSchema.parse(process.env);

export default config;
